# action.yml
name: 'OWASP Dependency Track'
description: 'Create SBOM and upload to OWASP Dependency Track'
branding:
  icon: 'check-square'
  color: 'green'

inputs:
  url:
    description: 'URL of OWASP Dependency Track REST API'
    required: true
    default: 'https://deptrack.example.com/'
  key:
    description: 'Key to access OWASP Dependency Track REST API'
    required: true
    default: 'USEAVALIDKEY'
  language:
    description: 'Programming language'
    required: true
    default: 'golang'
  delete:
    description: 'Delete project'
    required: false
    default: 'false'
  npm_token:
    description: 'Provide NPM token for installing packages'
    required: false
    default: 'USEAVALIDKEY'
  node_version:
    description: 'Specify NodeJS version'
    required: false
    default: '16.11.0'
  python_version:
    description: 'Specify Python version'
    required: false
    default: '3.9.7'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}
    - ${{ inputs.key }}
    - ${{ inputs.language }}
    - ${{ inputs.delete }}
    - ${{ inputs.npm_token }}
    - ${{ inputs.node_version }}
    - ${{ inputs.python_version }}
