# action.yml
name: 'OWASP Dependency Track'
description: 'Create SBOM and upload to OWASP Dependency Track'
branding:
  icon: 'check-square'
  color: 'green'

inputs:
  url:
    description: 'URL of OWASP Dependency Track REST API'
    required: true
    default: 'https://deptrack.example.com/'
  key:
    description: 'Key to access OWASP Dependency Track REST API'
    required: true
    default: 'USEAVALIDKEY'
  language:
    description: 'Programming language'
    required: true
    default: 'golang'
  delete:
    description: 'Delete project'
    required: false
    default: 'false'
  fail_on_critical:
    description: 'Fail on Critical vulnerabilities'
    required: false
    default: 'false'
  fail_on_high:
    description: 'Fail on High vulnerabilities'
    required: false
    default: 'false'

outputs:
  riskscore:
    description: 'String with the number of vulnerabilities found'
  critical:
    description: 'String with the number of vulnerabilities found'
  high:
    description: 'String with the number of vulnerabilities found'
  medium:
    description: 'String with the number of vulnerabilities found'
  low:
    description: 'String with the number of vulnerabilities found'
  fail_on_critical:
    description: 'String with the number of vulnerabilities found'
  fail_on_high:
    description: 'String with the number of vulnerabilities found'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}
    - ${{ inputs.key }}
    - ${{ inputs.language }}
    - ${{ inputs.delete }}
    - ${{ inputs.fail_on_critical }}
    - ${{ inputs.fail_on_high }}
