name: CI

# Controls when the action will run. 
on: [push]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Only run on default branch
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)

    # Only run with appropriate label
    if: contains(github.event.pull_request.labels.*.name, 'ready-for-ci')

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 
      
      # Generates a BoM and uploads it to OWASP Dependency Track
      - name: Generates SBOM and uploads to OWASP Dependency Track
        id: generateSBOM
        uses:  FuzzyGophers/action-owasp-dependecy-track@main
        with:
          url: 'https://deptrack.example.com'
          key: '${{ secrets.SECRET_OWASP_DT_KEY_BACKEND }}'
          npm_token: '${{ secrets.SECRET_OWASP_NPM_TOKEN }}'
          language: 'golang'
