name: CI

on: [push]

jobs:
  build:
    # Only run on default branch
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Generate SBOM and upload to OWASP Dependency Track
        id: generateSBOM
        uses:  FuzzyGophers/action-owasp-dependecy-track@main
        with:
          url: 'https://deptrack.example.com'
          key: '${{ secrets.OWASP_DT_KEY_BACKEND }}'
          npm_token: '${{ secrets.OWASP_NPM_TOKEN }}'
          language: 'golang'
